# Site settings
title: Ronak Shah
description: Operations Research | Quantitative Finance
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ronak Shah
user_description: I’m currently a Master’s student at Stony Brook University where I’m majoring in Applied Math and Statistics with Special focus on Optimization and Operations Research. I’ve experience working with Retail, Hospitality and Logistics. I also have an interest in writing Fantasy Fiction, worldbuilding and Conlanging.
user_title: Data Science
email: me@ronshah.tk
# twitter_username: lorem_ipsum
github_username:  hbk-ronak
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
